version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: "no"
    environment:
      MYSQL_DATABASE: stock_supporters
      MYSQL_USER: wrink
      MYSQL_PASSWORD: wrink
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "33333:8000"
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - db
      - postgres
      - redis

  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # frontend:
  #   build: C:\Users\wj830\Documents\GitHub\stock-supporters-frontend
  #   container_name: nextjs_app
  #   tty: true
  #   stdin_open: true
  #   command: tail -f /dev/null
  #   volumes:
  #     - C:\Users\wj830\Documents\GitHub\stock-supporters-frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:33333
  #   depends_on:
  #     - backend

volumes:
  pgdata:
